import Header from "@/components/header";
import { ImageKitProvider } from "@imagekit/next";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { Footer } from "@/components/footer";
import { Container } from "@/components/container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ImageKitProvider urlEndpoint={process.env.IMAGEKIT_URL_ENDPOINT}>
          <Header />
          <Container>{children}</Container>
          <Footer />
          <Toaster />
        </ImageKitProvider>
      </body>
    </html>
  );
}
